name: DashLord report

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["DashLord scans"]
    branches: [main]
    types:
      - completed

# allow only one concurrent report action
concurrency:
  cancel-in-progress: true
  group: report

jobs:
  website:
    runs-on: ubuntu-latest
    name: Website
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      # build the report
      - id: dashlord-report
        uses: SocialGouv/dashlord-actions/report@v1
        with:
          base-path: /dashlord-fabrique

      # to save the generated report.json as artifact
      - uses: actions/upload-artifact@v4
        with:
          path: report.json
          name: report
          if-no-files-found: error

      # save full report for history
      - uses: EndBug/add-and-commit@v7
        with:
          add: '["report.json"]'
          author_name: ${{ secrets.SOCIALGROOVYBOT_NAME }}
          author_email: ${{ secrets.SOCIALGROOVYBOT_EMAIL }}
          message: "chore: report update"

      # deploy build to gh-pages
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: build
